spring:
  application:
    name: zuulserver
server:
  port: 30002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
zuul:
  routes:
    time:
      path: /timeServer/**
      strip-prefix: false
    stock:
      path: /stockServer/**
      service-id: stockServer
    order:
      path: /orderServer/**
      service-id: orderServer
  ratelimit:
    enabled: true
    policies:
      time:
        limit: 10000
        refreshInterval: 10
      stock:
        limit: 5000
        refreshInterval: 10
      order:
        limit: 5000
        refreshInterval: 10
